import React, { useState } from 'react';
import { Alert, StyleSheet, Text, View, ScrollView, TouchableOpacity, FlatList, Image } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { MaterialIcons } from '@expo/vector-icons';
import { Ionicons } from '@expo/vector-icons';
import { Header } from '../components/Header';
import { SettingItem } from '../components/Cards';
import { ScreenContainer } from '../components/ScreenContainer';
import { clearTokens } from '../services/SpotifyAuth';
import { colors, typography } from '../themes/tokens';


const songs = [
    {
        id: '1',
        title: 'Midnight City',
        artist: 'M83',
        image: null
    },
    {
    id: '2',
    title: 'Weightless',
    artist: 'Marconi Union',
    image: null
    },
    {
    id: '3',
    title: 'Lose Yourself',
    artist: 'Eminem',
    image: null
    },
    {
    id: '4',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    image: null,
    },
    {
    id: '5',
    title: 'Mr. Brightside',
    artist: 'The Killers',
    image: null
    },

    {
    id: '6',
    title: 'Sunflower',
    artist: 'Post Malone',
    image: null,
    },

    {
    id: '7',
    title: 'Flashing Lights',
    artist: 'Kanye West',
    image: null,
    },

    {
    id: '8',
    title: 'Lemonade',
    artist: 'Tay-K',
    image: null,
    }

];

export default function ResultsScreen ({navigation}) {
    const [songList, setSongList] = useState(songs);
    const [isSaving, setIsSaving] = useState(false);
    const [isSaved, setIsSaved] = useState(false);

    const handleSaveToSpotify = () => {
        if (isSaved || isSaving) {
            return;
        }

        setIsSaving(true);

        setTimeout(() => {
            setIsSaving(false);
            setIsSaved(true);
            Alert.alert('Success', 'Playlist saved to your Spotify library!',
            [
                {
                    text: 'Ok',
                    onPress: () => navigation.navigate('Home')
                }
            ]
            );
        }, 1200);
    };

    const removeSong = (id) => {
        setSongList(prev => prev.filter(song => song.id !== id));
    }

    const renderSong = ({ item, index }) => {
        return (
            <View style={styles.songRow}>
            <Text style={styles.songIndex}>{index + 1}</Text>
        
            {item.image? (
            <Image source={{ uri: item.image }} style={styles.songImage} />
        ) : (
            <View style={styles.songPlaceholder}>
            <MaterialIcons name="music-note" size={22} color={colors.textSecondary} />
            </View>
        )}
            <View style={styles.songInfo}>
             <Text style={styles.songTitle} numberOfLines={1}>
              {item.title}
             </Text>
             <Text style={styles.songArtist} numberOfLines={1}>
              {item.artist}
             </Text>
            </View>

            <TouchableOpacity onPress={() => removeSong(item.id)} style={styles.removeButton}>
                <MaterialIcons name="close" size={20} color="#8E8E93"/>
            </TouchableOpacity>
            </View>
        );
    };

    return (
        <ScreenContainer>
            <Header
                title="Preview"
                leftAction={
                    <TouchableOpacity
                    style={styles.iconButton}
                    onPress={() => navigation.navigate('CategorySelection')}
                    >
                       <Ionicons name="chevron-back" size={28} color= "#FFFFFF" />
                    </TouchableOpacity>
                }
                rightAction={
                    <TouchableOpacity style={styles.iconButton}>
                        <MaterialIcons name="ios-share" size={22} color={colors.textPrimary} />
                    </TouchableOpacity>
                }
                />
                <View style={styles.topSection}>
                    <View style={styles.playlistRow}>
                        <View style={styles.playlistImage}>
                            <MaterialIcons name="music-note" size={34} color={colors.textSecondary} />
                        </View>
                        <View style={styles.playlistInfo}>
                            <Text style={styles.playlistTitle}>Chill & More</Text>
                            <Text style={styles.playlistSubtitle}>Generated by Sortify</Text>
                            <Text style={styles.playlistMeta}>6 SONGS VIBE</Text>
                        </View>
                    </View>
                </View>

                <FlatList
                    data={songList}
                    keyExtractor={(item) => item.id.toString()}
                    renderItem={renderSong}
                    showsVerticalScrollIndicator={false}
                    contentContainerStyle={styles.songList}
                    style={{ flex: 1 }}
                />

                <LinearGradient
                    colors={['rgba(11, 11, 11, 0)', '#0b0b0b']}
                    style={styles.bottom}
                >
                    <TouchableOpacity
                        style={[styles.saveButton, isSaved && styles.saveButtonSaved, isSaving && styles.saveButtonDisabled]}
                        onPress={handleSaveToSpotify}
                        activeOpacity={0.85}
                        disabled={isSaved || isSaving}
                    >
                        <MaterialIcons name={isSaved ? 'check' : 'music-note'} size={20} color='#0B0B0B' />
                        <Text style={[styles.saveButtonText, isSaved && styles.saveButtonSaved]}>
                            {isSaving ? 'Saving...' : isSaved ? 'Saved to Spotify' : 'Save to Spotify'}
                        </Text>
                    </TouchableOpacity>
                </LinearGradient>
        </ScreenContainer>
    );
}

const styles = StyleSheet.create({
    header: {
        height: 64,
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.06)',
    },

    headerTitle: {
        color: '#FFFFFF',
        fontSize: 24,
        fontWeight: '700',
        letterSpacing: -0.4,
    },

    iconButton: {
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },

    content: {
        paddingHorizontal: 16,
        paddingTop: 18,
        paddingBottom: 36,
    },
    songList: {
        paddingHorizontal: 16,
        paddingBottom: 120,
    },
    topSection: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 20,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: 'rgba(255,255,255,0.12)',
    },

    playlistRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
    },

    playlistImage: {
        width: 130,
        height: 130,
        borderRadius: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 18,
    },

    playlistInfo: {
        flex: 1,
        paddingTop: 10,
    },

    playlistTitle: {
        color: '#FFFFFF',
        fontSize: 28,
        fontWeight: '700',
        marginBottom: 4,
        letterSpacing: -0.5,
    },

    playlistSubtitle: {
        color: '#A7A7A7',
        fontSize: 17,
        fontWeight: '500',
        marginBottom: 6,
    },

    playlistMeta: {
        color: '#A7A7A7',
        fontSize: 14,
        fontWeight: '700',
        letterSpacing: 2,
        textTransform: 'uppercase',
    },

    songRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12
    },

    songIndex: {
        width: 26,
        color: '#8E8E93',
        fontSize: 16,
        fontWeight: '500',
        textAlign: 'left',
        marginRight: 12,
    },

    songImage: {
        width: 56,
        height: 56,
        borderRadius: 8,
    },

    songPlaceholder: {
        width: 56,
        height: 56,
        borderRadius: 8,
        backgroundColor: '#1A1A1A',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
        alignItems: 'center',
        justifyContent: 'center'
    },

    songInfo: {
        flex: 1,
        marginLeft: 14,
        justifyContent: 'center',
    },

    songTitle: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '600',
    },

    songArtist: {
        color: '#A7A7A7',
        fontSize: 16,
        fontWeight: '400',
    },
    
     songDuration: {
        color: '#7F8490',
        fontSize: 16,
        fontWeight: '500',
        marginLeft: 12,
    },

    bottom: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingTop: 80,
        paddingHorizontal: '5%',
        paddingBottom: 20,
    },
    saveButton: {
        backgroundColor: '#1ED760',
        borderRadius: 30,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        gap: 10,
    },

    saveButtonSaved: {
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderWidth: 1,
    },

    saveButtonDisabled: {
        opacity: 0.9,
    },

    saveButtonText: {
        color: '#0B0B0B',
        fontSize: 18,
        fontWeight: '500',
    },

    saveButtonTextSaved: {
        color: '#A7A7A7',
    },

    removeButton: {
        padding: 8,
        marginLeft: 8,
    }

});